/**
 * Icon types + build-time index metadata. These are the only things shared
 * across the whole app; everything else is co-located with its consumer.
 */

export type Pack = 'lucide' | 'phosphor' | 'iconoir'

export type Icon = {
  id: string
  pack: Pack
  name: string
  tags: string[]
  categories: string[]
  svg: string
  tokens: string[]
  neighbors: string[]
}

export type IconIndex = {
  version: number
  generatedAt: string
  count: number
  icons: Icon[]
}

// Build-time stats — regenerated by scripts/build-index.ts.
export const ICON_INDEX_HASH = '9a32b0d5'
export const ICON_COUNT = 4439
