/**
 * Icon types + build-time index metadata + the runtime loader. These are the
 * only things shared across the whole app; everything else is co-located with
 * its consumer (search is next to SearchInput, grid math next to GridCells,
 * etc.).
 *
 * `loadIcons` lives here — not under `components/` — because the icon index
 * is a global data resource keyed to the shared Icon type and the build-time
 * `ICON_*` constants below. Any future surface (previews, social cards,
 * background workers) can pull from the same cached fetch without reaching
 * into a component folder.
 */

export type Pack = 'lucide' | 'phosphor' | 'iconoir'

export type Icon = {
  id: string
  pack: Pack
  name: string
  tags: string[]
  categories: string[]
  svg: string
  tokens: string[]
  neighbors: string[]
}

export type IconIndex = {
  version: number
  generatedAt: string
  count: number
  icons: Icon[]
}

// Module-scoped cache — the fetch is idempotent and the payload is
// immutable for the lifetime of a build, so a single in-flight promise
// deduplicates concurrent callers during initial mount.
let cached: Promise<Icon[]> | null = null

export function loadIcons(): Promise<Icon[]> {
  if (cached) return cached
  cached = fetch('/icons.json', { cache: 'force-cache' })
    .then((r) => {
      if (!r.ok) throw new Error(`icons.json ${r.status}`)
      return r.json() as Promise<IconIndex>
    })
    .then((d) => d.icons)
  return cached
}

// Build-time stats — regenerated by scripts/build-index.ts. The rewrite
// regex matches these exact lines; keep them as single-line `export const`
// assignments.
export const ICON_INDEX_HASH = '704e890a'
export const ICON_COUNT = 4439
