export const DEFAULT_PROPERTIES: readonly string[] = [
  'color',
  'background-color',
  'background-image',
  'background-size',
  'background-position',
  'background-repeat',
  'background-clip',

  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'border-top-style',
  'border-right-style',
  'border-bottom-style',
  'border-left-style',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-right-radius',
  'border-bottom-left-radius',

  'outline-color',
  'outline-style',
  'outline-width',
  'outline-offset',

  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',

  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',

  'font-family',
  'font-size',
  'font-style',
  'font-weight',
  'font-variant',
  'line-height',
  'letter-spacing',
  'word-spacing',
  'text-align',
  'text-decoration',
  'text-transform',
  'text-indent',
  'white-space',

  'display',
  'visibility',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'z-index',
  'overflow-x',
  'overflow-y',

  'flex-direction',
  'flex-wrap',
  'justify-content',
  'align-items',
  'align-content',
  'gap',
  'row-gap',
  'column-gap',

  'grid-template-columns',
  'grid-template-rows',
  'grid-auto-flow',

  'box-shadow',
  'opacity',
  'transform',
  'transform-origin',
  'transition',
  'transition-duration',
  'transition-timing-function',
  'transition-delay',
  'transition-property',

  'filter',
  'backdrop-filter',
  'clip-path',
  'mask-image',
  'mix-blend-mode',

  'cursor',
  'pointer-events',
  'user-select',
  'accent-color',
  'caret-color',
]
